**Lab Assignment 4**

Question 1

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
addition=arr+2
multiplication=arr*3
division=arr/2
print(addition)
print(multiplication)
print(division)

ModuleNotFoundError: No module named 'numpy'

Question 2

In [4]:
arr=np.array([1,2,3,6,4,5])
reversed_arr=arr[::-1]
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])
most_frequent_x=np.bincount(x).argmax()
indices_x=np.where(x==most_frequent_x)
most_frequent_y=np.bincount(y).argmax()
indices_y=np.where(y==most_frequent_y)
print(reversed_arr)
print(most_frequent_x)
print(indices_x)
print(most_frequent_y)
print(indices_y)

[5 4 6 3 2 1]
1
(array([0, 5, 7, 8, 9]),)
1
(array([0, 1, 2]),)


Question 3

In [6]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
element_1_2=arr[0,1]
element_3_1=arr[2,0]
print(element_1_2)
print(element_3_1)

20
70


Question 4

In [7]:
naman=np.linspace(10,100,25)
dimensions=naman.ndim
shape=naman.shape
total_elements=naman.size
data_type=naman.dtype
total_bytes=naman.nbytes
reshaped_naman=naman.reshape(-1,1)
transpose_possible=naman.T.ndim==naman.ndim
print(naman)
print(dimensions)
print(shape)
print(total_elements)
print(data_type)
print(total_bytes)
print(reshaped_naman)
print(transpose_possible)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
25
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
True


Question 5

In [4]:
ucs420_naman=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
mean=np.mean(ucs420_naman)
median=np.median(ucs420_naman)
max_value=np.max(ucs420_naman)
min_value=np.min(ucs420_naman)
unique_elements=np.unique(ucs420_naman)
reshaped_ucs420_naman=ucs420_naman.reshape(4,3)
resized_ucs420_naman=np.resize(ucs420_naman,(2,3))
print(ucs420_naman)
print(mean)
print(median)
print(max_value)
print(min_value)
print(unique_elements)
print(reshaped_ucs420_naman)
print(resized_ucs420_naman)

NameError: name 'np' is not defined